#$ -cwd
#$ -q Annotation-1,Annotation-2,Annotation-3,Annotation-4
#$ -pe mpi 40
#$ -S /bin/bash

set -e
set -u
set -o pipefail

module load hisat2/v2.1.0
module load samtools/v1.12

REF=../../ref/Skeletonema_marinoi_Ref_v1.1.2.fasta
NAME=${PWD##*/}
READS=../../../00_data/trimmed/PRJEB33171/${NAME}_1.trimmed.fastq.gz

# Stricter mapping
# no-mixed and no-discordant included as they're used by the Trinity utility script `align_and_estimate_abundance`
hisat2 -p $NSLOTS --no-unal --no-mixed --no-discordant --max-intronlen 10000 -x ${REF} -U ${READS} -S ${NAME}.sam

samtools view -@ $NSLOTS -b -o ${NAME}.bam ${NAME}.sam
rm ${NAME}.sam
samtools sort -@ $NSLOTS -o ${NAME}_sorted.bam ${NAME}.bam
rm ${NAME}.bam
samtools index ${NAME}_sorted.bam ${NAME}_sorted.bai
