#$ -cwd
#$ -q Annotation-1,Annotation-2,Annotation-3
#$ -pe mpi 40
#$ -S /bin/bash

set -e
set -u
set -o pipefail

module load hisat2/v2.1.0
module load samtools/v1.12

REF=../../ref/Skeletonema_marinoi_Ref_v1.1.2.fasta
NAME=${PWD##*/}
MATE1=$(ls ../../../00_data/trimmed/PRJNA912555/*/${NAME}*R1*trimmed.fastq.gz)
MATE2=$(ls ../../../00_data/trimmed/PRJNA912555/*/${NAME}*R2*trimmed.fastq.gz)

# Stricter mapping
# no-mixed and no-discordant included as they're used by the Trinity utility script `align_and_estimate_abundance`
hisat2 -p $NSLOTS --no-unal --no-mixed --no-discordant --max-intronlen 10000 -x ${REF} -1 ${MATE1} -2 ${MATE2} -S ${NAME}.sam

samtools view -@ $NSLOTS -b -o ${NAME}.bam ${NAME}.sam
rm ${NAME}.sam
samtools sort -@ $NSLOTS -o ${NAME}_sorted.bam ${NAME}.bam
rm ${NAME}.bam
samtools index ${NAME}_sorted.bam ${NAME}_sorted.bai
